<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpanan_model extends CI_Model
{

    public $table = 'simpanan';
    public $id = 'id_simpanan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('$this->id', $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_list_simpanan()
    {
        $this->db->order_by('noanggota', $this->order);
        return $this->db->get('total_simpanan')->result();
    }

    // get data by id
    function get_by_noanggota($noanggota)
    {
        $this->db->where('noanggota', $noanggota);
        return $this->db->get($this->table)->result();
    }

    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_simpanan', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('noanggota', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('user_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_simpanan', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('noanggota', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('user_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Simpanan_model.php */
/* Location: ./application/models/Simpanan_model.php */
/* Please DO NOT modify this information : */
/* This file generated by Andre Bhaskoro (+62 82 333 817 317) At : 2016-12-05 10:11:52 */
/* http://bhas.web.id */