<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_koperasi_model extends CI_Model
{

    public $table = 'transaksi_kop';
    public $id = 'id_transaksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('anggota', 'anggota.noanggota = transaksi_kop.noanggota', 'left');
        $this->db->join('barang', 'barang.id_jenis = transaksi_kop.id_jenis', 'left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_noanggota($noanggota)
    {
        $this->db->join('barang', 'barang.id_jenis = transaksi_kop.id_jenis', 'left');
        $this->db->where('noanggota', $noanggota);
        return $this->db->get($this->table)->result();
    }

    function get_total_transaksi($noanggota)
    {
        $sql = "SELECT sum(jumlah) as total_transaksi
                FROM transaksi_kop
                WHERE noanggota = '$noanggota'";
        $query = $this->db->query($sql);
        return $query->row();
    }

    function get_total_transaksi_kop()
    {
        $sql = "SELECT sum(jumlah) as total_transaksi
                FROM transaksi_kop";
        $query = $this->db->query($sql);
        return $query->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_transaksi', $q);
    	$this->db->or_like('tgl', $q);
    	$this->db->or_like('noanggota', $q);
    	$this->db->or_like('id_jenis', $q);
    	$this->db->or_like('jumlah', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_transaksi', $q);
    	$this->db->or_like('tgl', $q);
    	$this->db->or_like('noanggota', $q);
    	$this->db->or_like('id_jenis', $q);
    	$this->db->or_like('jumlah', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_koperasi_model.php */
/* Location: ./application/models/Transaksi_koperasi_model.php */
/* Please DO NOT modify this information : */
/* This file generated by Andre Bhaskoro (+62 82 333 817 317) At : 2016-12-06 04:59:08 */
/* http://bhas.web.id */